openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/publishers:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: 'The field to sort the list by.'
          example: name
          required: false
          schema:
            type: string
            description: 'The field to sort the list by.'
            example: name
        -
          in: query
          name: 'filter[name]'
          description: 'Filter by publisher name containing value.'
          example: comics
          required: false
          schema:
            type: string
            description: 'Filter by publisher name containing value.'
            example: comics
        -
          in: query
          name: 'filter[country]'
          description: 'Filter by publisher country.'
          example: USA
          required: false
          schema:
            type: string
            description: 'Filter by publisher country.'
            example: USA
        -
          in: query
          name: 'filter[founded-year]'
          description: 'Filter by publisher founded year.'
          example: 1940
          required: false
          schema:
            type: integer
            description: 'Filter by publisher founded year.'
            example: 1940
        -
          in: query
          name: 'filter[founded-year-between]'
          description: 'Filter by publisher founded year in the given range.'
          example: '1940,1990'
          required: false
          schema:
            type: string
            description: 'Filter by publisher founded year in the given range.'
            example: '1940,1990'
        -
          in: query
          name: 'page[number]'
          description: 'The page number (default 1).'
          example: 2
          required: false
          schema:
            type: integer
            description: 'The page number (default 1).'
            example: 2
        -
          in: query
          name: 'page[size]'
          description: 'The page size (default 30).'
          example: 10
          required: false
          schema:
            type: integer
            description: 'The page size (default 30).'
            example: 10
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 342
                      name: 'Bernhard, Harvey and Dicki'
                      founded-at: '2020'
                      website-url: 'http://www.feil.com/in-saepe-officiis-voluptates'
                      twitter-url: 'http://green.com/tempora-ea-velit-corrupti-et-molestias-dicta-molestias.html'
                      address: "3275 Leuschke Pines Apt. 875\nOsbaldohaven, NY 88441"
                      city: 'New Lee'
                      state: ''
                      zip: 43707-8655
                      country: IOT
                      created-at: '2022-01-25T20:07:06+00:00'
                      updated-at: '2022-01-25T20:07:06+00:00'
                    -
                      id: 343
                      name: 'Metz Inc'
                      founded-at: '2018'
                      website-url: 'https://www.lesch.biz/et-molestiae-sapiente-repellendus-assumenda-modi-dolor-sed'
                      twitter-url: 'http://watsica.com/blanditiis-voluptas-amet-suscipit-eveniet-perferendis-harum-et'
                      address: "12280 Dortha Island\nEast Estevanchester, AL 36471"
                      city: 'New Emely'
                      state: ''
                      zip: 87741-7112
                      country: JPN
                      created-at: '2022-01-25T20:07:06+00:00'
                      updated-at: '2022-01-25T20:07:06+00:00'
                  links:
                    first: '/?page=1'
                    last: '/?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: '/?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: /
                    per_page: '30'
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 342
                        name: 'Bernhard, Harvey and Dicki'
                        founded-at: '2020'
                        website-url: 'http://www.feil.com/in-saepe-officiis-voluptates'
                        twitter-url: 'http://green.com/tempora-ea-velit-corrupti-et-molestias-dicta-molestias.html'
                        address: "3275 Leuschke Pines Apt. 875\nOsbaldohaven, NY 88441"
                        city: 'New Lee'
                        state: ''
                        zip: 43707-8655
                        country: IOT
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                      -
                        id: 343
                        name: 'Metz Inc'
                        founded-at: '2018'
                        website-url: 'https://www.lesch.biz/et-molestiae-sapiente-repellendus-assumenda-modi-dolor-sed'
                        twitter-url: 'http://watsica.com/blanditiis-voluptas-amet-suscipit-eveniet-perferendis-harum-et'
                        address: "12280 Dortha Island\nEast Estevanchester, AL 36471"
                        city: 'New Emely'
                        state: ''
                        zip: 87741-7112
                        country: JPN
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: '/?page=1'
                      last: '/?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: '/?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: /
                      per_page: '30'
                      to: 2
                      total: 2
      tags:
        - Publisher
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    field:
                      - 'Error message'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      field:
                        - 'Error message'
      tags:
        - Publisher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the publisher.'
                  example: iusto
                founded_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2022.'
                  example: 896
                founded_month:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 12.'
                  example: 12
                founded_day:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 31.'
                  example: 3
                website_url:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: hrhfefakzfjksisgqymeoivrvvnfinlvdxrodwdmgiq
                twitter_url:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: hrzekcfmmvdcwssajxinnhezzeoqvztctbiqqzxtbjbyggnkpaxjyygvhumgmbqipxa
              required:
                - name
  '/api/v1/publishers/{id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 344
                    name: 'Hackett, Schmidt and Flatley'
                    founded-at: '1979'
                    website-url: 'http://www.kohler.com/nihil-occaecati-ut-odio-nihil-possimus'
                    twitter-url: 'https://schmidt.com/soluta-fuga-fugiat-voluptatibus-aut-officia.html'
                    address: "28948 Friedrich Road Apt. 389\nNew Kiel, RI 51868"
                    city: Markusborough
                    state: ''
                    zip: '45343'
                    country: BRA
                    created-at: '2022-01-25T20:07:06+00:00'
                    updated-at: '2022-01-25T20:07:06+00:00'
                properties:
                  data:
                    type: object
                    example:
                      id: 344
                      name: 'Hackett, Schmidt and Flatley'
                      founded-at: '1979'
                      website-url: 'http://www.kohler.com/nihil-occaecati-ut-odio-nihil-possimus'
                      twitter-url: 'https://schmidt.com/soluta-fuga-fugiat-voluptatibus-aut-officia.html'
                      address: "28948 Friedrich Road Apt. 389\nNew Kiel, RI 51868"
                      city: Markusborough
                      state: ''
                      zip: '45343'
                      country: BRA
                      created-at: '2022-01-25T20:07:06+00:00'
                      updated-at: '2022-01-25T20:07:06+00:00'
      tags:
        - Publisher
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    field:
                      - 'Error message'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      field:
                        - 'Error message'
      tags:
        - Publisher
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: ztkcqazfvtnfioilfr
                founded_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2022.'
                  example: 537
                founded_month:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 12.'
                  example: 0
                founded_day:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 31.'
                  example: 21
                website_url:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: cuoustipavqalgzuhsnkjbjywhglujlbcoqndakgnaltzsgdcnpppmrihswqoxxbdgrssebonbjsbfzgymezxtxfysxfgxdbrqlqhkmhpxjhpnnloohdkqgjwnsgjlbxgpqfssdvhcsmkneruzibqipqtn
                twitter_url:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: ujsrlnpzrwbtdrmxjhdgrdqwcugeasqmnxvsfhyqnvsjtbhpfyimldmsxzxvttdzaupgsmqwajfnwwsaakkzkoiwelmwlufklnyelvv
    delete:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Resource not found.'
                properties:
                  message:
                    type: string
                    example: 'Resource not found.'
      tags:
        - Publisher
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the publisher.'
        example: 20
        required: true
        schema:
          type: integer
  /api/v1/series:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: 'The field to sort the list by.'
          example: title
          required: false
          schema:
            type: string
            description: 'The field to sort the list by.'
            example: title
        -
          in: query
          name: 'page[number]'
          description: 'The page number (default 1).'
          example: 2
          required: false
          schema:
            type: integer
            description: 'The page number (default 1).'
            example: 2
        -
          in: query
          name: 'page[size]'
          description: 'The page size (default 30).'
          example: 10
          required: false
          schema:
            type: integer
            description: 'The page size (default 30).'
            example: 10
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 53
                      title: 'Devan Wolf'
                      volume: 9
                      description: 'Quia ut quos fugit voluptatem explicabo omnis. Ut delectus porro deleniti accusantium omnis. Ut quisquam animi occaecati dolorum deserunt dolorem. Velit assumenda natus culpa incidunt quo.'
                      start-year: '2021'
                      end-year: '1993'
                      rating: aut
                      created-at: '1976-01-26T12:52:34+00:00'
                      updated-at: '1970-05-10T09:06:26+00:00'
                      publisher:
                        id: 347
                        name: 'Gorczany PLC'
                        founded-at: '1973'
                        website-url: 'http://www.marquardt.com/molestiae-maxime-sed-et-quod-repudiandae'
                        twitter-url: 'http://www.greenholt.com/'
                        address: "65298 Zieme Underpass Suite 994\nDemetrisbury, TX 27993-8207"
                        city: Hintzland
                        state: ''
                        zip: 86234-2772
                        country: ABW
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                    -
                      id: 54
                      title: 'Antwan Connelly PhD'
                      volume: 66
                      description: 'Et saepe veritatis nemo. Et sit voluptatibus et explicabo architecto. Eius repellat culpa et culpa. Aperiam adipisci maiores quasi provident doloribus.'
                      start-year: '1988'
                      end-year: '1978'
                      rating: ea
                      created-at: '2015-05-26T01:38:44+00:00'
                      updated-at: '1978-09-11T18:17:11+00:00'
                      publisher:
                        id: 348
                        name: 'O''Keefe-Klein'
                        founded-at: '2007'
                        website-url: 'http://farrell.com/harum-tempore-perferendis-ratione-eum-hic-dolor.html'
                        twitter-url: 'http://www.schaefer.com/aperiam-temporibus-nihil-voluptatem-voluptatem-quidem-quos-consequuntur'
                        address: "628 VonRueden Island\nNicolashaven, MN 76531"
                        city: 'Lake Elianeshire'
                        state: ''
                        zip: 98029-8391
                        country: PYF
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                  links:
                    first: '/?page=1'
                    last: '/?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: '/?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: /
                    per_page: '30'
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 53
                        title: 'Devan Wolf'
                        volume: 9
                        description: 'Quia ut quos fugit voluptatem explicabo omnis. Ut delectus porro deleniti accusantium omnis. Ut quisquam animi occaecati dolorum deserunt dolorem. Velit assumenda natus culpa incidunt quo.'
                        start-year: '2021'
                        end-year: '1993'
                        rating: aut
                        created-at: '1976-01-26T12:52:34+00:00'
                        updated-at: '1970-05-10T09:06:26+00:00'
                        publisher:
                          id: 347
                          name: 'Gorczany PLC'
                          founded-at: '1973'
                          website-url: 'http://www.marquardt.com/molestiae-maxime-sed-et-quod-repudiandae'
                          twitter-url: 'http://www.greenholt.com/'
                          address: "65298 Zieme Underpass Suite 994\nDemetrisbury, TX 27993-8207"
                          city: Hintzland
                          state: ''
                          zip: 86234-2772
                          country: ABW
                          created-at: '2022-01-25T20:07:06+00:00'
                          updated-at: '2022-01-25T20:07:06+00:00'
                      -
                        id: 54
                        title: 'Antwan Connelly PhD'
                        volume: 66
                        description: 'Et saepe veritatis nemo. Et sit voluptatibus et explicabo architecto. Eius repellat culpa et culpa. Aperiam adipisci maiores quasi provident doloribus.'
                        start-year: '1988'
                        end-year: '1978'
                        rating: ea
                        created-at: '2015-05-26T01:38:44+00:00'
                        updated-at: '1978-09-11T18:17:11+00:00'
                        publisher:
                          id: 348
                          name: 'O''Keefe-Klein'
                          founded-at: '2007'
                          website-url: 'http://farrell.com/harum-tempore-perferendis-ratione-eum-hic-dolor.html'
                          twitter-url: 'http://www.schaefer.com/aperiam-temporibus-nihil-voluptatem-voluptatem-quidem-quos-consequuntur'
                          address: "628 VonRueden Island\nNicolashaven, MN 76531"
                          city: 'Lake Elianeshire'
                          state: ''
                          zip: 98029-8391
                          country: PYF
                          created-at: '2022-01-25T20:07:06+00:00'
                          updated-at: '2022-01-25T20:07:06+00:00'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: '/?page=1'
                      last: '/?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: '/?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: /
                      per_page: '30'
                      to: 2
                      total: 2
      tags:
        - Series
  '/api/v1/series/{id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 55
                    title: 'Miss Ebba O''Hara'
                    volume: 80
                    description: 'Iusto porro occaecati natus asperiores dicta ab blanditiis. Porro architecto architecto et. Nisi ut quia est quas voluptates qui voluptatem. Consectetur quia omnis voluptatibus deleniti illum.'
                    start-year: '2009'
                    end-year: '1974'
                    rating: aut
                    created-at: '2002-03-07T00:37:06+00:00'
                    updated-at: '2010-12-30T08:08:49+00:00'
                    publisher:
                      id: 349
                      name: Kuphal-Windler
                      founded-at: '1994'
                      website-url: 'http://mccullough.com/vel-labore-non-distinctio-tenetur-fuga.html'
                      twitter-url: 'http://corwin.info/consequatur-unde-quos-rerum-neque-eius-saepe'
                      address: "184 Cristal Streets Suite 830\nSouth Lamont, UT 74826"
                      city: Gilesstad
                      state: ''
                      zip: 46008-2201
                      country: UZB
                      created-at: '2022-01-25T20:07:06+00:00'
                      updated-at: '2022-01-25T20:07:06+00:00'
                properties:
                  data:
                    type: object
                    example:
                      id: 55
                      title: 'Miss Ebba O''Hara'
                      volume: 80
                      description: 'Iusto porro occaecati natus asperiores dicta ab blanditiis. Porro architecto architecto et. Nisi ut quia est quas voluptates qui voluptatem. Consectetur quia omnis voluptatibus deleniti illum.'
                      start-year: '2009'
                      end-year: '1974'
                      rating: aut
                      created-at: '2002-03-07T00:37:06+00:00'
                      updated-at: '2010-12-30T08:08:49+00:00'
                      publisher:
                        id: 349
                        name: Kuphal-Windler
                        founded-at: '1994'
                        website-url: 'http://mccullough.com/vel-labore-non-distinctio-tenetur-fuga.html'
                        twitter-url: 'http://corwin.info/consequatur-unde-quos-rerum-neque-eius-saepe'
                        address: "184 Cristal Streets Suite 830\nSouth Lamont, UT 74826"
                        city: Gilesstad
                        state: ''
                        zip: 46008-2201
                        country: UZB
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
      tags:
        - Series
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    field:
                      - 'Error message'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      field:
                        - 'Error message'
      tags:
        - Series
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 150 characters.'
                  example: hvcjxkyuyfmaaepfhnietoltrqewsvtuqicyocziltpufqrybpvywqlgzzuazepusrywqttatmxehxtowzkfmsrbblsdluumzjafe
                volume:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 0
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: mnbxnizjhkwwjeibnxfldyykrbgjrqrhqcezdorqflfxdthzgvwnureiquqlxqzrcfkvjucyvrahvrjcibgfjgtsmjlroodcgbjbvkoyzblcrkxtxcbpwwiqldkvxusqlrkbkxhrstmxdmtiszktycmjudrsffucfuojsagfqdzeapvpsuoigrdlzonpybqfsxxtdfeqbdptdkliefrwizukavoratzmszzxusvxejqywt
                start_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2023.'
                  example: 254
                end_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2023.'
                  example: 190
                rating:
                  type: string
                  description: 'Must not be greater than 30 characters.'
                  example: ugrspjpoeuivbtjdykwnogfdbvuy
    delete:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Resource not found.'
                properties:
                  message:
                    type: string
                    example: 'Resource not found.'
      tags:
        - Series
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the series.'
        example: 14
        required: true
        schema:
          type: integer
  '/api/v1/publishers/{publisher}/series':
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Accepted
                properties:
                  message:
                    type: string
                    example: Accepted
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    field:
                      - 'Error message'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      field:
                        - 'Error message'
      tags:
        - Series
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 150 characters.'
                  example: pertoudoudnsfsrvbprbemlletxdmgwecekniuoozmlswiyfkgdxzxlbekwybyatlzxcfdsmaorgvonvlnhuppslhflb
                volume:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 0
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: qfwetjtgrdelrkwajrjhenpiprudgupcmcuxzsxdvhgltqzpgdnwdrscugqkdesncjikjrjxhgqxppclwkcbyzcoqxzutuotelrpolfckshaieridfurviumkvimzpgbdjtlhyinbooxyrkifngtsgavwmvmcnekqdbkdqjgtjwqrsqjgiiyegqisrkawelopygdglfxnquynjqtuxhwbqxtdzlpdvdokakezlzydcakntzkgqlgprkmozlgxdfbiwxupgtqrwhlefcjzdyrmxmxyedkypdqbakhqjq
                start_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2023.'
                  example: 450
                end_year:
                  type: integer
                  description: 'Must be at least 1900. Must not be greater than 2023.'
                  example: 352
                rating:
                  type: string
                  description: 'Must not be greater than 30 characters.'
                  example: btbugufuvlhcz
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: 'The field to sort the list by.'
          example: title
          required: false
          schema:
            type: string
            description: 'The field to sort the list by.'
            example: title
        -
          in: query
          name: 'page[number]'
          description: 'The page number (default 1).'
          example: 2
          required: false
          schema:
            type: integer
            description: 'The page number (default 1).'
            example: 2
        -
          in: query
          name: 'page[size]'
          description: 'The page size (default 30).'
          example: 10
          required: false
          schema:
            type: integer
            description: 'The page size (default 30).'
            example: 10
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 51
                      title: 'Mr. Devyn Conn'
                      volume: 88
                      description: 'Molestiae et eius sunt placeat nostrum quasi. Doloremque culpa incidunt velit. Facere facilis esse sed totam tempore aliquid.'
                      start-year: '1992'
                      end-year: '2007'
                      rating: laborum
                      created-at: '1975-11-17T17:26:18+00:00'
                      updated-at: '1989-02-15T11:04:42+00:00'
                      publisher:
                        id: 345
                        name: Hilpert-Morar
                        founded-at: '2012'
                        website-url: 'http://lehner.net/autem-at-neque-rem-dicta-molestias-dolorem-quidem'
                        twitter-url: 'http://www.hauck.info/sit-minus-alias-est-similique-eum-laborum.html'
                        address: "226 Kautzer Road Suite 502\nDevonside, OH 22283-5743"
                        city: 'East Johnpaulview'
                        state: ''
                        zip: 32779-5731
                        country: BFA
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                    -
                      id: 52
                      title: 'Lorenzo Bahringer'
                      volume: 47
                      description: 'Fugiat labore molestias pariatur doloribus molestiae. Dolores ex aliquid dolores ab ut sit. Quasi nisi accusamus occaecati cum et. Qui veniam soluta sequi optio porro aut cumque.'
                      start-year: '1994'
                      end-year: '1984'
                      rating: ea
                      created-at: '1976-05-26T10:33:40+00:00'
                      updated-at: '1986-07-31T01:52:40+00:00'
                      publisher:
                        id: 346
                        name: Donnelly-Parisian
                        founded-at: '2001'
                        website-url: 'https://www.wisoky.com/omnis-rerum-architecto-et-eum-quae'
                        twitter-url: 'https://price.com/sed-debitis-temporibus-sapiente-facilis-vero-aut-accusamus.html'
                        address: "30427 Federico Pass Apt. 368\nMarcside, WY 11907"
                        city: 'East Muhammad'
                        state: ''
                        zip: 46191-4858
                        country: GTM
                        created-at: '2022-01-25T20:07:06+00:00'
                        updated-at: '2022-01-25T20:07:06+00:00'
                  links:
                    first: '/?page=1'
                    last: '/?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: '/?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: /
                    per_page: '30'
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 51
                        title: 'Mr. Devyn Conn'
                        volume: 88
                        description: 'Molestiae et eius sunt placeat nostrum quasi. Doloremque culpa incidunt velit. Facere facilis esse sed totam tempore aliquid.'
                        start-year: '1992'
                        end-year: '2007'
                        rating: laborum
                        created-at: '1975-11-17T17:26:18+00:00'
                        updated-at: '1989-02-15T11:04:42+00:00'
                        publisher:
                          id: 345
                          name: Hilpert-Morar
                          founded-at: '2012'
                          website-url: 'http://lehner.net/autem-at-neque-rem-dicta-molestias-dolorem-quidem'
                          twitter-url: 'http://www.hauck.info/sit-minus-alias-est-similique-eum-laborum.html'
                          address: "226 Kautzer Road Suite 502\nDevonside, OH 22283-5743"
                          city: 'East Johnpaulview'
                          state: ''
                          zip: 32779-5731
                          country: BFA
                          created-at: '2022-01-25T20:07:06+00:00'
                          updated-at: '2022-01-25T20:07:06+00:00'
                      -
                        id: 52
                        title: 'Lorenzo Bahringer'
                        volume: 47
                        description: 'Fugiat labore molestias pariatur doloribus molestiae. Dolores ex aliquid dolores ab ut sit. Quasi nisi accusamus occaecati cum et. Qui veniam soluta sequi optio porro aut cumque.'
                        start-year: '1994'
                        end-year: '1984'
                        rating: ea
                        created-at: '1976-05-26T10:33:40+00:00'
                        updated-at: '1986-07-31T01:52:40+00:00'
                        publisher:
                          id: 346
                          name: Donnelly-Parisian
                          founded-at: '2001'
                          website-url: 'https://www.wisoky.com/omnis-rerum-architecto-et-eum-quae'
                          twitter-url: 'https://price.com/sed-debitis-temporibus-sapiente-facilis-vero-aut-accusamus.html'
                          address: "30427 Federico Pass Apt. 368\nMarcside, WY 11907"
                          city: 'East Muhammad'
                          state: ''
                          zip: 46191-4858
                          country: GTM
                          created-at: '2022-01-25T20:07:06+00:00'
                          updated-at: '2022-01-25T20:07:06+00:00'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: '/?page=1'
                      last: '/?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: '/?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: /
                      per_page: '30'
                      to: 2
                      total: 2
      tags:
        - Series
    parameters:
      -
        in: path
        name: publisher
        description: ''
        example: 14
        required: true
        schema:
          type: integer
tags:
  -
    name: Publisher
    description: ''
  -
    name: Series
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
